-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 08:12:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_BlogCfpt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_BlogCfpt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_BlogCfpt` DEFAULT CHARACTER SET utf8 ;
USE `db_BlogCfpt` ;

-- -----------------------------------------------------
-- Table `db_BlogCfpt`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_BlogCfpt`.`post` ;

CREATE TABLE IF NOT EXISTS `db_BlogCfpt`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `commentairePost` VARCHAR(50) NULL,
  `creationDatePost` TIMESTAMP NULL,
  `modificationDatePost` TIMESTAMP NULL,
  PRIMARY KEY (`idPost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_BlogCfpt`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_BlogCfpt`.`media` ;

CREATE TABLE IF NOT EXISTS `db_BlogCfpt`.`media` (
  `idMedia` INT NOT NULL AUTO_INCREMENT,
  `typeMedia` VARCHAR(50) NULL,
  `nomFichierMedia` VARCHAR(50) NULL,
  `creationDate` TIMESTAMP NULL,
  `modificationDate` TIMESTAMP NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idMedia`, `idPost`),
  INDEX `fk_media_post_idx` (`idPost` ASC),
  CONSTRAINT `fk_media_post`
    FOREIGN KEY (`idPost`)
    REFERENCES `db_BlogCfpt`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
